name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    -master

jobs:

  # Linting process with Selene
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Foreman & all tools listed in foreman.toml
    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
          version: "^1.0.0"
          token: ${{ SECRETS.GITHUB_TOKEN }}

    # Run selene against the src directory
    - name: Lint
      run: |
        selene ./src